booksQuotesApp/Models/Quote.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace booksQuotesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Quote
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Quote")]
        [StringLength(250)]
        public string QuoteText { get; set; }

        
        [Display(Name = "Image URL")]
        public string ImageURL { get; set; }

        public Nullable<int> BookId { get; set; }
    
        public virtual Book Book { get; set; }
    }
}

booksQuotesApp/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using booksQuotesApp.Models;

namespace booksQuotesApp.Controllers
{
    public class AuthorsController : Controller
    {
        private myBookQuoteDBEntities db = new myBookQuoteDBEntities();

        // GET: Authors
        public ActionResult Index(string searchString)
        {
            //create IQueryable variable
            var authors = from a in db.Authors
                          select a;

            //filter by search string
            if (!String.IsNullOrEmpty(searchString))
            {
                authors = authors.Where(a => a.Name.Contains(searchString));
                
            }

            return View(authors);
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound(); 
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create(string returnView2)
        {
            
            TempData["returnView2"] = returnView2;
           


            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Biography,ImageURL")] Author author)
        {
            //if (author.ImageURL == null)
            //{
            //    author.ImageURL = ;
            //}

            try
            {
              

                if (ModelState.IsValid)
                {
                    db.Authors.Add(author);
                    db.SaveChanges();

                    if (Convert.ToString(TempData["returnView2"]) == "createBookView")
                    {  

                        return RedirectToAction("Create","Books");
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes.  Try again, and if the problem persists, contact your system administrator.");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Biography,ImageURL")] Author author)
        {

        
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int AssociatedBooksNumber = 0;
            Author author = db.Authors.Find(id);
            AssociatedBooksNumber = author.Books.Count();
            //only allow delete if there are no books or films associated with detective
            if (AssociatedBooksNumber == 0)
            {
                db.Authors.Remove(author);
                db.SaveChanges();
            }
            else
            {
                TempData["MyErrorMessage"] = "You cannot delete this author while there are books linked to them.";
                TempData["DeletionError"] = true;
                return RedirectToAction("Delete", new { id = id });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

booksQuotesApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using booksQuotesApp.Models;

namespace booksQuotesApp.Controllers
{
    public class BooksController : Controller
    {
        private myBookQuoteDBEntities db = new myBookQuoteDBEntities();

        // GET: Books
        public ActionResult Index(string searchString, string currentFilter)
        {
            //create IQueryable variable
            var books = from b in db.Books
                          select b;

            //filter by search string
            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Name.Contains(searchString));

            }

            return View(books);
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create(string returnView)
        {
            ViewBag.AuthorId = new SelectList(db.Authors, "Id", "Name"); /*ID is the value that will be passed to authorID field, name is text that will be displayed in dropdownList*/

            if (returnView != null)
            {
                TempData["returnView"] = returnView;
                return View();
            }

            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Genre,Synopsis,ImageURL,AuthorId")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                if (Convert.ToString(TempData["returnView"]) == "createQuoteView")
                {
                    return RedirectToAction("Create", "Quotes");
                }

                else {
                    return RedirectToAction("Index");
                     }
            }

            ViewBag.AuthorId = new SelectList(db.Authors, "Id", "Name", book.AuthorId);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorId = new SelectList(db.Authors, "Id", "Name", book.AuthorId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Genre,Synopsis,ImageURL,AuthorId")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Authors, "Id", "Name", book.AuthorId);
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int AssociatedQuotesNumber = 0;
            Book book = db.Books.Find(id);
            AssociatedQuotesNumber = book.Quotes.Count();
            //only allow delete if there are no books or films associated with detective
            if (AssociatedQuotesNumber == 0)
            {
                db.Books.Remove(book);
                db.SaveChanges();
            }
            else
            {
                TempData["MyErrorMessage"] = "You cannot delete this book while there are quotes linked to them.";
                TempData["DeletionError"] = true;
                return RedirectToAction("Delete", new { id = id });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

booksQuotesApp/Controllers/QuotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using booksQuotesApp.Models;

namespace booksQuotesApp.Controllers
{
    public class QuotesController : Controller
    {
        private myBookQuoteDBEntities db = new myBookQuoteDBEntities();

        // GET: Quotes
        public ActionResult Index(string searchString)
        {
            //create IQueryable variable
            var quotes = db.Quotes.Include(b => b.Book).Include(b => b.Book.Author);
                          

            //filter by search string
            if (!String.IsNullOrEmpty(searchString))
            {

                
                quotes = quotes.Where(s => s.QuoteText.Contains(searchString) || s.Book.Name.Contains(searchString) || s.Book.Author.Name.Contains(searchString));
            }


            return View(quotes); 
        }

        // GET: Quotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.Quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            return View(quote);
        }

        // GET: Quotes/Create
        public ActionResult Create()
        {
            ViewBag.BookId = new SelectList(db.Books, "Id", "Name");
            return View();
        }

        // POST: Quotes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,QuoteText,ImageURL,BookId")] Quote quote)
        {
            if (quote.ImageURL == null)
            {
                quote.ImageURL = "https://scontent-lhr3-1.xx.fbcdn.net/v/t1.0-9/42239378_1812501612181421_279511227468611584_n.jpg?_nc_cat=104&oh=011fb15800d85e23ff5502a32a0aff92&oe=5C1F2BDE";
            }
            if (ModelState.IsValid)
            {
                db.Quotes.Add(quote);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BookId = new SelectList(db.Books, "Id", "Name", quote.BookId);
            return View(quote);
        }

        // GET: Quotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.Quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookId = new SelectList(db.Books, "Id", "Name", quote.BookId);
            return View(quote);
        }

        // POST: Quotes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,QuoteText,ImageURL,BookId")] Quote quote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookId = new SelectList(db.Books, "Id", "Name", quote.BookId);
            return View(quote);
        }

        // GET: Quotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.Quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            return View(quote);
        }

        // POST: Quotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quote quote = db.Quotes.Find(id);
            db.Quotes.Remove(quote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

booksQuotesApp/Views/Quotes/Create.cshtml
@model booksQuotesApp.Models.Quote

@{
    ViewBag.Title = "Create";
}


<div class="AddContainer container text-center">
    <h2>Add Quote</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.QuoteText, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QuoteText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QuoteText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BookId, "Book", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BookId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="cantFind text-left">
                You can't find your book in the list?  @Html.ActionLink(" Add New Book here", "Create", "Books", new { returnView = "createQuoteView" }, new { @class = "add" })
            </div>

            <div class="row">
                <br/>
                <br/>
                <br/>
                <div class="col-md-offset-2 col-md-6 text-left">
                    <input type="submit" value="Create" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                </div>

                
            </div>
            
        </div>
        
    }

    




</div> 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

booksQuotesApp/Views/Quotes/Delete.cshtml
@model booksQuotesApp.Models.Quote

@{
    ViewBag.Title = "Delete";
}

<div class="container AddContainer">

    <h2>Delete Quote</h2>
    <hr />
    <br/>
    
    <h3>Are you sure you want to delete this?</h3>
    <br />
    <div>
       
       
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.QuoteText)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.QuoteText)
            </dd>


            <dt>
                Book
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Book.Name)
            </dd>
            <dt>
                Author
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Book.Author.Name)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <br/>
                <br/>
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>

    </div>

booksQuotesApp/Views/Quotes/Details.cshtml
@model booksQuotesApp.Models.Quote

@{
    ViewBag.Title = "Details";
}


<div class="container detailsContainer">

    <div class="text-center">

        <h2>Quote details</h2>
  
        <div class="detailsBody">
            <div class="text-left col-md-8">


                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.QuoteText):
                    </dt>

                    <dd class="text-left">
                        @Html.DisplayFor(model => model.QuoteText)
                    </dd>





                    <dt>
                        Author:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Book.Author.Name)
                    </dd>

                    <dt>
                        Book:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Book.Name)
                    </dd>

                </dl>
            </div>

            <div class="col-md-4">

                <img class="myImgDetails" src="@Url.Content(Model.Book.ImageURL)" />
            </div>
        </div>
        <div class="text-left col-md-6">
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id },new {@class="btn btn-default"}) |
                @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-default" }) |
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </p>
        </div>
       

  
    </div>
</div>

booksQuotesApp/Views/Quotes/Edit.cshtml
@model booksQuotesApp.Models.Quote

@{
    ViewBag.Title = "Edit";
}

<div class="AddContainer container text-center">
    <h2>Edit Quote</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.QuoteText, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QuoteText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QuoteText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BookId, "Book", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BookId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="row">
                <div class="col-md-offset-2 col-md-6 text-left">
                    <input type="submit" value="Save" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                </div>
                
            </div>
        </div>
    }

  
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

booksQuotesApp/Views/Quotes/Index.cshtml
@model IEnumerable<booksQuotesApp.Models.Quote>

@{
    ViewBag.Title = "Quotes";
}

<div class="Bg text-center">
    <div class="headingContainer">
        <h1 class="iQuote">IQuote.</h1>
        <br />
       
   
        <h2> Your Favorite Book Quotes.</h2>
     
    </div>
        
     <div class="searchContainer">
        @using (Html.BeginForm("Index", "Quotes", "FormMethod.Get"))
        {
            <p>

                @Html.TextBox("searchString", null, new { @placeholder = "Find by keyword, author Name or book name..", @class = "quoteSearch" })

                <input type="submit" value="Search" />
            </p>
            
        }
         <br/>

        <span>@Html.ActionLink("Add a quote", "Create", null, new { @class = "btn btn-default" })</span>
    </div>
</div>


<div class="row">
    @foreach (var quote in Model)
    {


        <div style="background-image:url(@Url.Content(quote.ImageURL)) ; background-size:cover; height:320px;" class="col-md-3 text-center">

            <div class="quoteContainer">
                <div><a href="@Url.Action("Details","Quotes", new {id = quote.Id })">"@Html.DisplayFor(model => quote.QuoteText)"</a></div>
                <br />

                <div class="quotedetails">
                    <a href="@Url.Action("Details","Authors", new {id = quote.Book.AuthorId })">
                        -@Html.DisplayFor(model => quote.Book.Author.Name),
                    </a> <span>
                        <a href="@Url.Action("Details","Books", new {id = quote.BookId })">
                            @Html.DisplayFor(model=> quote.Book.Name)
                        </a>
                    </span>
                </div>
            </div>
        </div>

        
    }
</div>